# Generated by Django 3.1.4 on 2021-01-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exams',
        ),
    ]
