# Generated by Django 3.1.4 on 2021-02-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='class_pk',
            new_name='class_id',
        ),
    ]
