# Generated by Django 3.1.4 on 2021-02-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20210205_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='comments',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('ph', 'Physics'), ('mt', 'Mathematics'), ('cs', 'Computer Science')], max_length=20),
        ),
    ]
