# Generated by Django 3.1.4 on 2021-01-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210108_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('ph', 'Physics'), ('mt', 'Math'), ('cs', 'Computer Science'), ('bi', 'Biology'), ('ch', 'Chemistry')], max_length=20),
        ),
    ]
