# Generated by Django 3.1.4 on 2021-02-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210207_0344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
