# Generated by Django 3.1.4 on 2021-02-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
