# Generated by Django 3.1.4 on 2021-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='viewed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='viewed',
            field=models.IntegerField(null=True),
        ),
    ]
