# Generated by Django 3.1.4 on 2021-02-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
