# Generated by Django 3.1.4 on 2021-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_auto_20210119_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='viewed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='viewed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
