# Generated by Django 3.1.4 on 2021-01-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20210119_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
