# Generated by Django 3.1.4 on 2021-01-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_exam_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
