# Generated by Django 3.1.6 on 2021-02-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20210208_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('topic', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.FileField(upload_to='documents/class_files')),
            ],
        ),
    ]
