# Generated by Django 3.1.4 on 2021-01-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
