# Generated by Django 3.1.6 on 2021-02-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_auto_20210208_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='code',
        ),
    ]
