# Generated by Django 3.1.4 on 2021-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_auto_20210121_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
