# Generated by Django 3.1.4 on 2021-01-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_exam_profile_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
