# Generated by Django 3.1.4 on 2021-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_auto_20210123_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='other_info',
        ),
        migrations.AddField(
            model_name='exam',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
