# Generated by Django 3.1.4 on 2021-01-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_auto_20210127_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
