# Generated by Django 3.1.4 on 2021-01-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
