# Generated by Django 3.1.4 on 2021-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0027_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(max_length=64),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(max_length=64),
        ),
    ]
