# Generated by Django 3.1.4 on 2021-01-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_auto_20210130_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(),
        ),
    ]
