# Generated by Django 3.1.4 on 2021-01-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0029_auto_20210130_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
