# Generated by Django 3.1.4 on 2021-02-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='files',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='files',
        ),
    ]
