# Generated by Django 3.1.4 on 2021-02-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0035_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
