# Generated by Django 3.1.4 on 2021-02-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0036_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('tagline', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('content', models.FileField(upload_to='documents/class_files')),
            ],
        ),
    ]
