# Generated by Django 3.1.4 on 2021-02-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0037_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
