# Generated by Django 3.1.4 on 2021-02-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0038_auto_20210201_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='class_id',
            new_name='class_pk',
        ),
    ]
