# Generated by Django 3.1.4 on 2021-02-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0040_auto_20210204_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
