# Generated by Django 3.1.4 on 2021-02-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0041_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_pk', models.IntegerField()),
                ('topic', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.FileField(upload_to='documents/class_files')),
            ],
        ),
    ]
